### ISSUE TITLE
PHP 7.3.5 Error

### ISSUE THREAD

**Issue by alexiscm72** [piantgrunger/yii2-stisla#5]
Error installing composer global require "fxp/composer-asset-plugin:~1.1"

[InvalidArgumentException]
  Package fxp/composer-asset-plugin at version ~1.1 has a PHP requirement incompatible with your PHP version, PHP ext
  ensions and Composer version

Tested with php 7.3.5

**Comment by piantgrunger** [comment]
fxp/composer-asset-plugin:*
